#!/bin/sh

# This script adds all untracked files, commits and immediately pushes to origin

message=$1 # First parameter will be the commit message

if [ ! -z "$1" ] # checking if the commit message is present. If not then aborting.
then
  git add .
  git commit -am "$message"
  git push
  gh pr create -w
else
  echo "Commit message is not provided"
fi