#!/bin/sh

# Add all files, commit, and push to origin

message=$1

if [ -z "$message" ]; then
  echo "Commit message is not provided"
  exit 1
fi

echo "Files to be committed:"
git status --short
printf "\nProceed? [Y/n]: "
read answer

if [ "$answer" = "n" ] || [ "$answer" = "N" ]; then
  echo "Aborted."
  exit 1
fi

git add .
git commit -am "$message"
git push
