#!/bin/sh

# Add all files, commit, push, and create a PR

message=$1

if [ -z "$message" ]; then
  echo "Commit message is not provided"
  exit 1
fi

git cp "$message" || exit 1
gh pr create -w --title "$message" --body ""
